services:
  web:
    image: ghcr.io/monkeyscloud/monkeyslegion-docker
    restart: unless-stopped
    command: ["-n"]
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8080:80"
    environment:
      APP_ENV: dev
      DB_HOST: db
      DB_DATABASE: ml_skeleton
      DB_USERNAME: ml
      DB_PASSWORD: secret
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 30s
      retries: 3
  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ml_skeleton
      MYSQL_USER: ml
      MYSQL_PASSWORD: secret
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD --silent"]
      interval: 30s
      timeout: 5s
      retries: 5